### ISSUE TITLE
Generates broken *.EXE files

### ISSUE THREAD

**Issue by gadielisawesome** [FlyTechVideos/BluescreenSimulator#134] opened 2023-01-23 08:08 UTC
If you apply a custom color, it displays an error message, then reverts back to the basic blue BSOD of Windows 10. Not sure why it does this.

All I can say though is that _**this project is probably never going to be updated again.**_

**Comment by SamyoFox** [comment] 2023-03-19 17:20
I unfortunately can't reproduce this on my own, would you please send me the exact configuration you're using? (What text you entered, the colors, etc.)

**Comment by FlyTechVideos** [comment] 2023-08-03 14:19
@gadielisawesome 
Should be fixed with 3.4.0 -> Get it here: https://github.com/FlyTechVideos/BluescreenSimulator/releases/tag/3.4.0
If it still occurs, please post a screenshot of the error message and your configuration settings. Thank you!

**Closed by FlyTechVideos** 2023-08-03 14:19 UTC
Labels: bug
